title: Manual de Sobrevivência
description: Como sobreviver dentro do curso de Sistemas de Informação do IFS
author: Manual de Sobrevivência
logo: /static/img/avatar.png
github: https://github.com/AlessonC/Manual-de-Sobrevivencia/
about:

baseurl: ""
url: #

allowsearch: true

disqus_shortname: 
google_analytics: 

enableTags: true
tagarray: []


paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
